name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - main  # Adjust this to your default or deployment branch

jobs:
  build-n-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup UV
        uses: astral-sh/setup-uv@v6.1.0
        with:
          version: latest
          activate-environment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: uv sync --group dev

      - name: Run Tests
        run: uv run pytest

      - name: Build Project
        run: uv build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      # Optional: Publish to PyPI (uncomment to enable)
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
